## Student Performance Liner Regression - Multi Variable

In [1]:
#imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('Student_performance.csv')
df.head(10)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
5,3,78,No,9,6,61.0
6,7,73,Yes,5,6,63.0
7,8,45,Yes,4,6,42.0
8,5,77,No,8,2,61.0
9,4,89,No,4,0,69.0

# Data preprossessing

In [3]:
# step -1: Extracurricular Actvivties columns is yes or no, but we need to convert into 1 and 0
print(df['Extracurricular Activities'].unique())
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes': 1, 'No': 0}) # maps yes and no  
df.head(10)

['Yes' 'No']

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
5,3,78,0,9,6,61.0
6,7,73,1,5,6,63.0
7,8,45,1,4,6,42.0
8,5,77,0,8,2,61.0
9,4,89,0,4,0,69.0

In [4]:
#find any values are null
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [27]:
X = df.drop('Performance Index', axis=1)
y = df['Performance Index']


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
X_train.head(10)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,0,7,5
1561,2,48,1,7,6
1670,2,81,0,7,2
6087,2,46,0,6,1
6669,8,47,0,9,0
5933,3,56,0,4,4
8829,3,51,1,4,1
7945,9,93,1,5,2
3508,4,61,1,6,5
2002,4,96,1,8,0

In [28]:
# Create scaled copies
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# Compute statistics from RAW X_train
hours_mean = X_train['Hours Studied'].mean()
hours_std = X_train['Hours Studied'].std()

scores_mean = X_train['Previous Scores'].mean()
scores_std = X_train['Previous Scores'].std()

sleep_mean = X_train['Sleep Hours'].mean()
sleep_std = X_train['Sleep Hours'].std()

sample_mean = X_train['Sample Question Papers Practiced'].mean()
sample_std = X_train['Sample Question Papers Practiced'].std()

In [29]:
# Normalize X_train_scaled
X_train_scaled['Hours Studied'] = (
    X_train['Hours Studied'] - hours_mean
) / hours_std

X_train_scaled['Previous Scores'] = (
    X_train['Previous Scores'] - scores_mean
) / scores_std

X_train_scaled['Sleep Hours'] = (
    X_train['Sleep Hours'] - sleep_mean
) / sleep_std

X_train_scaled['Sample Question Papers Practiced'] = (
    X_train['Sample Question Papers Practiced'] - sample_mean
) / sample_std

In [30]:
X_test_scaled['Hours Studied'] = (
    X_test['Hours Studied'] - hours_mean
) / hours_std

X_test_scaled['Previous Scores'] = (
    X_test['Previous Scores'] - scores_mean
) / scores_std

X_test_scaled['Sleep Hours'] = (
    X_test['Sleep Hours'] - sleep_mean
) / sleep_std

X_test_scaled['Sample Question Papers Practiced'] = (
    X_test['Sample Question Papers Practiced'] - sample_mean
) / sample_std

In [ ]:
print(X_train.head())
print("\n")
print(X_train_scaled.head())

X_train:
9254    0.006455
1561   -1.149676
1670   -1.149676
6087   -1.149676
6669    1.162586
Name: Hours Studied, dtype: float64

X_train mean/std:
-3.286260152890463e-17
0.9999999999999554

X_train_scaled:
9254    0.006455
1561   -1.149676
1670   -1.149676
6087   -1.149676
6669    1.162586
Name: Hours Studied, dtype: float64

In [ ]:
#Adding Bias term
X_train_scaled['Bias'] = 1
X_test_scaled['Bias'] = 1

In [40]:
#convert data into matrix
X_train_matrix = X_train_scaled.values
print(X_train_matrix[:5])
y_train_vector = y_train.values
print(y_train_vector[:5])
X_test_matrix = X_test_scaled.values
print(X_test_matrix[:5])
y_test_vector = y_test.values
print(y_test_vector[:5])

[[ 0.00645506 -1.1837704   0.          0.26987161  0.13403274  1.        ]
 [-1.14967559 -1.24142811  1.          0.26987161  0.48353142  1.        ]
 [-1.14967559  0.66127625  0.          0.26987161 -0.91446328  1.        ]
 [-1.14967559 -1.35674353  0.         -0.31888565 -1.26396196  1.        ]
 [ 1.16258571 -1.29908582  0.          1.44738613 -1.61346063  1.        ]]
[36. 25. 59. 22. 40.]
[[ 0.00645506 -0.03061624  0.          0.85862887 -0.91446328  1.        ]
 [-1.14967559 -1.35674353  1.         -1.49640017  1.18252877  1.        ]
 [ 0.77720883 -0.78016645  1.          0.26987161  0.13403274  1.        ]
 [ 0.39183195 -1.58737436  1.          0.85862887  0.13403274  1.        ]
 [ 0.77720883 -0.95313957  0.         -1.49640017  0.48353142  1.        ]]
[51. 20. 46. 28. 41.]

In [41]:
#Initialzing Weights, learning rate and number of iterations
weights = np.zeros(X_train_matrix.shape[1])
print(weights)
learning_rate = 0.01
iterations = 1000

[0. 0. 0. 0. 0. 0.]

X      @     w
(m,n)       (n,)
↓            ↓
students   weights

In [43]:
for i in range(iterations):
    #finding dot product
    X_train_dot = np.dot(X_train_matrix,weights)
   
    #finding error
    error = X_train_dot  - y_train_vector
    
    #finding gradient
    X_train_transpose = X_train_matrix.T
    gradient_dot = np.dot(X_train_transpose,error)
    
    gradient = gradient_dot/X_train_matrix.shape[0]
    
    #updating weights
    weights = weights-(learning_rate*gradient)

In [ ]:
#training the test set
X_test_dot = np.dot(X_test_matrix,weights)
print(X_test_dot[:5])

[54.4002862  22.80956884 48.10562103 31.49719848 42.67812432]

In [46]:
#MSE
test_error = X_test_dot - y_test_vector
test_error = test_error**2
mse_sum = np.sum(test_error)
mse = mse_sum/test_error.shape[0]
print(mse)

4.137420689007048

In [47]:
#RMSE
rmse  = np.sqrt(mse)
print(rmse)

2.034065065086918

In [50]:
# R squared
upper_error = y_test_vector - X_test_dot
upper_error = upper_error**2
upper_error_sum = np.sum(upper_error)
print(upper_error_sum)
y_test_mean = np.mean(y_test_vector)
lower_error = y_test_vector - y_test_mean
lower_error  = lower_error**2
lower_error_sum = np.sum(lower_error)
print(lower_error_sum)

R_2 = 1-(upper_error_sum/lower_error_sum)
print(R_2)

8274.841378014096
741170.2320000001
0.9888354375003905