### Linear Regression

In [66]:
import pandas as pd

In [67]:
fish = pd.read_csv("D:\Jupyter Notebook\Linear regression\Fish[1].csv")
fish

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [68]:
print(fish['Species'].unique())
print(fish['Species'].mode())

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
0    Perch
Name: Species, dtype: object

In [69]:
print(fish.groupby('Species')['Weight'].mean().sort_values(ascending=False))
print("----------------------------")
print(fish.groupby('Species')['Length1'].mean().sort_values(ascending=False))
print("----------------------------")
print(fish.groupby('Species')['Length2'].mean().sort_values(ascending=False))

Species
Pike         718.705882
Bream        617.828571
Whitefish    531.000000
Perch        382.239286
Parkki       154.818182
Roach        152.050000
Smelt         11.178571
Name: Weight, dtype: float64
----------------------------
Species
Pike         42.476471
Bream        30.305714
Whitefish    28.800000
Perch        25.735714
Roach        20.645000
Parkki       18.727273
Smelt        11.257143
Name: Length1, dtype: float64
----------------------------
Species
Pike         45.482353
Bream        33.108571
Whitefish    31.316667
Perch        27.892857
Roach        22.275000
Parkki       20.345455
Smelt        11.921429
Name: Length2, dtype: float64

In [70]:
print(fish.groupby('Species')['Length3'].mean().sort_values(ascending=False))
print("----------------------------")
print(fish.groupby('Species')['Height'].mean().sort_values(ascending=False))
print("----------------------------")
print(fish.groupby('Species')['Width'].mean().sort_values(ascending=False))

Species
Pike         48.717647
Bream        38.354286
Whitefish    34.316667
Perch        29.571429
Roach        24.970000
Parkki       22.790909
Smelt        13.035714
Name: Length3, dtype: float64
----------------------------
Species
Bream        15.183211
Whitefish    10.027167
Parkki        8.962427
Perch         7.861870
Pike          7.713771
Roach         6.694795
Smelt         2.209371
Name: Height, dtype: float64
----------------------------
Species
Whitefish    5.473050
Bream        5.427614
Pike         5.086382
Perch        4.745723
Roach        3.657850
Parkki       3.220736
Smelt        1.340093
Name: Width, dtype: float64

In [71]:
fish.info()
fish.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Species  159 non-null    object
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

### Correlation between Lenghts
How correlation works?
we use the corr() function to see how 2 attributes are related to each other
output will be a nxn matrix with values[-1,1]

+1 → perfect positive relation (they increase together).

0 → no linear relation.

–1 → perfect negative relation.

In [72]:
fish[['Length1','Length2','Length3']].corr()

          Length1   Length2   Length3
Length1  1.000000  0.999517  0.992031
Length2  0.999517  1.000000  0.994103
Length3  0.992031  0.994103  1.000000

These correlation values (~0.99) show near-perfect positive correlation among Length1, Length2, and Length3.

Implication:

They carry identical information.

Keeping all three adds redundancy and causes multicollinearity, which can distort model weights (especially in linear or logistic regression).

In [75]:
# Now we can take average of the lenghts and add the columns
average_length = fish[['Length1','Length2','Length3']].mean(axis=1)
fish['Average_Length'] = average_length
print(fish.groupby('Species')['Average_Length'].mean().sort_values(ascending=False))

Species
Pike         45.558824
Bream        33.922857
Whitefish    31.477778
Perch        27.733333
Roach        22.630000
Parkki       20.621212
Smelt        12.071429
Name: Average_Length, dtype: float64